name: Publish PowerShell Module

on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          Get-PackageProvider | Where-Object Name -eq 'nuget' | Install-PackageProvider -Force
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Publish-Module -Path "./$($env:GITHUB_REPOSITORY.Split('/')[1])" -NuGetApiKey $env:NUGET_KEY -Verbose
